package tugas_java2_01;
import java.sql.Connection;
import java.sql.ResultSet ;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author This-PC
 */
public class FrameBarang extends javax.swing.JFrame {

    /** Creates new form FrameBarang */

     private Statement stat;
 private ResultSet rs;
 DefaultTableModel model;
 private final String judulKolom[]={"No.","Kode Barang","Nama Barang","Kategori","Satuan","Harga","Jumlah"};
 private String[][] dataBarang;
 String objKategori[]={"Alat Tulis","Kertas","Buku","ATK"};
 
 private void setModeltabel(){
 // membuat tampilan model tabel
 model = new DefaultTableModel(dataBarang,judulKolom);
 tblBarang.setModel(model);
 }
    private void view_data(){
    model.getDataVector().removeAllElements();
    try {
            int no=1;
            String sql = "select * from barang";
            koneksi objkoneksi=new koneksi();
            Connection con =objkoneksi.bukakoneksi();
            stat = con.createStatement();
            rs = stat.executeQuery(sql);
            while(rs.next()){
            model.addRow(new
            Object[]{no++,rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6)});
        }

                            } catch (Exception e) {
 }
 }
    public FrameBarang() {
        initComponents();
         setModeltabel();
        view_data();
        
       tblBarang.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int row = tblBarang.getSelectedRow();
                if(row!=-1){
                    String tKode =(tblBarang.getModel().getValueAt(row, 1).toString());
                    String tNama =(tblBarang.getModel().getValueAt(row, 2).toString());
                    String tKategori =(tblBarang.getModel().getValueAt(row, 3).toString());
                    String tSatuan =(tblBarang.getModel().getValueAt(row, 4).toString());
                    String tHarga =(tblBarang.getModel().getValueAt(row, 5).toString());
                    String tJumlah =(tblBarang.getModel().getValueAt(row, 6).toString());
                    
                    txtkode.setText(tKode);
                    txtnamabarang.setText(tNama);
                    txtharga.setText(tHarga);
                    txtjumlah.setText(tJumlah);
                    btnUbah.setEnabled(true);
                    btnHapus.setEnabled(true);
                    btnSimpan.setEnabled(false);
                    
                    
                    cbkategori.setSelectedItem(tKategori);
                     if (tSatuan.equals("pcs")) {
                         rbpcs.setSelected(true);
                     }else if(tSatuan.equals("box")){
                         rbbox.setSelected(true);
                     }else{
                         rbrim.setSelected(true);
                     }
                }
            }
       }); 
    

     for (String object : objKategori){
            cbkategori.addItem(object);
    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupKategori = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        txtnamabarang = new javax.swing.JTextField();
        cbkategori = new javax.swing.JComboBox();
        rbpcs = new javax.swing.JRadioButton();
        rbbox = new javax.swing.JRadioButton();
        rbrim = new javax.swing.JRadioButton();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBarang = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18));
        jLabel1.setText("DATA BARANG");

        jLabel2.setText("NAMA BARANG :");

        jLabel3.setText("KODE BARANG :");

        jLabel4.setText("KATEGORI       :");

        jLabel5.setText("SATUAN           :");

        jLabel6.setText("JUMLAH           :");

        jLabel7.setText("HARGA             :");

        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txthargaKeyTyped(evt);
            }
        });

        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahKeyTyped(evt);
            }
        });

        cbkategori.setName(""); // NOI18N

        buttonGroupKategori.add(rbpcs);
        rbpcs.setText("pcs");

        buttonGroupKategori.add(rbbox);
        rbbox.setText("box");

        buttonGroupKategori.add(rbrim);
        rbrim.setText("rim");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("BATAL");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        tblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6))
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbkategori, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtnamabarang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addComponent(txtkode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbpcs)
                                .addGap(18, 18, 18)
                                .addComponent(rbbox)
                                .addGap(8, 8, 8)
                                .addComponent(rbrim))
                            .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSimpan)
                                .addGap(18, 18, 18)
                                .addComponent(btnBatal)
                                .addGap(18, 18, 18)
                                .addComponent(btnUbah, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus)
                                .addGap(80, 80, 80)))))
                .addContainerGap(293, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(89, 89, 89)
                    .addComponent(jLabel3)
                    .addContainerGap(686, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbpcs)
                    .addComponent(rbrim)
                    .addComponent(rbbox))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnBatal)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(144, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(75, 75, 75)
                    .addComponent(jLabel3)
                    .addContainerGap(549, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
// TODO add your handling code here:
try{
    koneksi objkoneksi=new koneksi();
    Connection con=objkoneksi.bukakoneksi();
    String sql="DELETE from barang where kodebarang='"+txtkode.getText()+"'";
    stat=con.createStatement();
    stat.executeUpdate(sql);
    JOptionPane.showMessageDialog(null,"Data Berhasil Di Hapus");
    awal();
    view_data();
}
catch(Exception e)
{
    System.out.println("gagal="+e.getMessage());
}    
}//GEN-LAST:event_btnHapusActionPerformed

private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
// TODO add your handling code here:
     String satuan;
 if(rbpcs.isSelected()){
 satuan = "pcs";
 }else if(rbbox.isSelected()){
 satuan = "box";
 }else{
 satuan = "rim";
 }
 try{
 koneksi objkoneksi=new koneksi();
 Connection con=objkoneksi.bukakoneksi();
 String sql="INSERT INTO barang VALUES('"+txtkode.getText()+"','"+txtnamabarang.getText()+"','"+cbkategori.getSelectedItem()+"','"+satuan+"','"+txtharga.getText()+"','"+txtjumlah.getText()+"')";
 stat = con.createStatement();
 stat.execute(sql);

 JOptionPane.showMessageDialog(null, "Data Berhasil di Input");
 txtkode.setText("");
 txtnamabarang.setText("");
 txtharga.setText("");
 txtjumlah.setText("");
 cbkategori.setSelectedIndex(0);
 rbpcs.setSelected(false);
 rbbox.setSelected(false);
 rbrim.setSelected(false);
 txtkode.requestFocus();

 }
  catch (Exception e) 
 {
 System.out.println("gagal="+e.getMessage());
 }
}//GEN-LAST:event_btnSimpanActionPerformed

private void txthargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyTyped
// TODO add your handling code here:
     char cDigit = evt.getKeyChar();
 if(txtharga.getText().length()<10){
 if(!Character.isDigit(cDigit)){
 evt.consume();
 }
 }else{
 evt.consume();
 }
}//GEN-LAST:event_txthargaKeyTyped

private void txtjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyTyped
// TODO add your handling code here:
     char cDigit = evt.getKeyChar();
 if(txtjumlah.getText().length()<5){
 if(!Character.isDigit(cDigit)){
 evt.consume();
 }
 }else{
 evt.consume();
 }
}//GEN-LAST:event_txtjumlahKeyTyped

private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
// TODO add your handling code here:
    awal(); 
}
private void awal (){
    txtkode.setText("");
    txtnamabarang.setText("");
    txtjumlah.setText("");
    txtharga.setText("");
    cbkategori.setSelectedIndex(0);
    rbpcs.setSelected(false);
    rbbox.setSelected(false);
    rbrim.setSelected(false);
    txtkode.requestFocus();
}//GEN-LAST:event_btnBatalActionPerformed

private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
// TODO add your handling code here:
 if(cbkategori.getSelectedIndex()!=0){
    String satuan;
    if(rbpcs.isSelected()){
        satuan="pcs";
    }else if(rbbox.isSelected()){
        satuan="box";
    }else if(rbrim.isSelected()){
        satuan="rim";
    }else{
        satuan=null;
    }
    try{
        koneksi objkoneksi=new koneksi();
        Connection con=objkoneksi.bukakoneksi();
        String sql="UPDATE barang SET namabarang='"+txtnamabarang.getText()+"',kategori='"+cbkategori.getSelectedItem()+"',"+"satuan='"+satuan+"',harga='"+txtharga.getText()+"',jumlah='"+txtjumlah.getText()+"'where kodebarang='"+txtkode.getText()+"'";
        stat =con.createStatement();
        stat.executeUpdate(sql);
        
    javax.swing.JOptionPane.showMessageDialog(null, "Data berhasil di ubah");
    awal();
    view_data();
    }catch (Exception e)
    {
        System.out.println("gagal="+e.getMessage());
    }
}else{
    JOptionPane.showMessageDialog(null,"Piih kategori barang","notifikasi",2);
}
}//GEN-LAST:event_btnUbahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrameBarang().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.ButtonGroup buttonGroupKategori;
    private javax.swing.JComboBox cbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbbox;
    private javax.swing.JRadioButton rbpcs;
    private javax.swing.JRadioButton rbrim;
    private javax.swing.JTable tblBarang;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnamabarang;
    // End of variables declaration//GEN-END:variables

 
    

}
